//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uczestnik
    {
        public int idUczestnika { get; set; }
        public string imieNazwisko { get; set; }
        public string email { get; set; }
        public string nrTelefonu { get; set; }
    }
}
