//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wiadomosci
    {
        public int idWiadomosci { get; set; }
        public string imieNazwisko { get; set; }
        public string adresEmail { get; set; }
        public Nullable<System.DateTime> dataOdebrania { get; set; }
        public string tekstWiadomosci { get; set; }
    }
}
